<!--NAVIGATION-->
<[step05 Numpy함수학습](step04_NumpyFun.ipynb)>  |

# NumPy Basics

### 1. Review를 위한 단계
- 방식 : 기존 실습 자료 및 검색을 하면서 이해하고 주석 달기
- 파일명 : **step03_Review이름.ipynb** 제출

In [5]:
#Numpy API import
import numpy as np 

## The NumPy ndarray: A Multidimensional Array Object

In [6]:
# 2 x 3 난수 matrix array 생성
data = np.random.randn(2, 3) 
data

array([[ 2.30434907,  0.59086992, -0.21550109],
       [ 0.81394786, -1.22499858,  2.33182687]])

In [7]:
# 난수 matrix array에 연산자 적용
data * 10  
data + data

array([[ 4.60869813,  1.18173985, -0.43100217],
       [ 1.62789571, -2.44999717,  4.66365374]])

In [9]:
# 난수 matrix array의 데이터 타입 및 차원 확인
print(data.shape)
print(data.dtype, data.ndim)

(2, 3)
float64 2


### Creating ndarrays

In [14]:
# ndarray = N차원의 배열 객체
# ndarray는 같은 종류의 데이터만 배열에 담을 수 있음
# list 객체를 np.array를 사용 해 배열로 변환
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
# ndarray의 데이터 타입 및 차원 확인
print(arr1.shape, arr1.ndim, arr1.dtype)
print(arr2.shape, arr2.ndim, arr2.dtype)

(5,) 1 float64
(2, 4) 2 int32


In [9]:
# np.zeros() 함수는 괄호 안의 숫자만큼 '0' 으로 배열 생성
np.zeros(10)
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
# 0부터 괄호안의 숫자 만큼의 정수 배열 값을 '배열'로 반환
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays

In [15]:
# N차원 배열객체 생성 시 dtype 설정 가능
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [26]:
# N차원 배열객체의 dtype 변경 가능
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int32
float64


In [27]:
# N차원 배열객체의 dtype 변경 
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr)
arr.astype(np.int32)

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]


array([ 3, -1, -2,  0, 12, 10])

In [39]:
# 다른 배열의 dtype으로 변경 
int_array = np.arange(10)
print(int_array)
print(int_array.dtype)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
print(calibers)
print(calibers.dtype)
print(int_array.astype(calibers.dtype))
print(int_array.astype(calibers.dtype).dtype)

[0 1 2 3 4 5 6 7 8 9]
int32
[0.22  0.27  0.357 0.38  0.44  0.5  ]
float64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


### Arithmetic with NumPy Arrays

In [57]:
# 크기가 같은 두개의 숫자형 배열의 산술 연산
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
print('-'* 20)
print(arr * arr)
print('-'* 20)
print(arr - arr)

[[1. 2. 3.]
 [4. 5. 6.]]
--------------------
[[ 1.  4.  9.]
 [16. 25. 36.]]
--------------------
[[0. 0. 0.]
 [0. 0. 0.]]


In [61]:
print(1 / arr)
print('-'* 35)
print(arr ** 0.5)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
-----------------------------------
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [46]:
# 배열의 대소 비교
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### Basic Indexing and Slicing

In [48]:
# arr[](index)로 array의 value값 선택 및 수정
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8] = 12 # index 5 ~ 7번째까지 value=12로 변경
print(arr)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


In [49]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [51]:
arr_slice[1] = 12345
print(arr)

[    0     1     2     3     4    12 12345    12     8     9]


In [21]:
# 원본데이터에 영향을 줌
arr_slice[:] = 64 # arr_slice[:] = arr[5:8]
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [129]:
# 2차원 배열의 index[2]값
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d.ndim)
print(arr2d[2])

2
[7 8 9]


In [114]:
print(arr2d[0][2])
print(arr2d[0, 2])

3
3


In [115]:
# 4 x 3 array
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [116]:
# 4 x 3 array의 index[0]
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [117]:
# old_values = arr3d의 index[0]의 복제본 
# arr3d(원본)에는 영향을 안미침
old_values = arr3d[0].copy()
arr3d[0] = 42
print(arr3d)
print('-' * 20)
arr3d[0] = old_values
print(arr3d)
print(arr3d.ndim, arr3d.shape)

[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
--------------------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3 (2, 2, 3)


In [118]:
# 3차원 array의 index[1, 0] 값
arr3d[1, 0]

array([7, 8, 9])

In [119]:
# x = 3차원 array의 index[1]값
# x = 2 x 3 배열의 2차원 array
x = arr3d[1]
print(x.shape, x.ndim)
print(x)
x[0]

(2, 3) 2
[[ 7  8  9]
 [10 11 12]]


array([7, 8, 9])

#### Indexing with slices

In [120]:
# arr = 2차원 2 x 3 array
# arr[1:6] = index[1] ~ index[5] 까지
print(arr)
print(arr.dtype, arr.ndim, arr.shape)
print('-' * 15)
print(arr[1:6])

[[1. 2. 3.]
 [4. 5. 6.]]
float64 2 (2, 3)
---------------
[[4. 5. 6.]]


In [121]:
# arr2d = 2차원 3 x 3 array
# arr2d[:2] = index[0] ~ index[1] 까지
print(arr2d)
print(arr2d.dtype, arr2d.ndim, arr2d.shape)
print('-' * 15)
print(arr2d[:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int32 2 (3, 3)
---------------
[[1 2 3]
 [4 5 6]]


In [122]:
# arr2d[:2, 1:] = arr2d[:2]의 [1:]
# arr2d[:2][1:] = [4 5 6]]
print(arr2d)
print('-'* 10)
print(arr2d[:2])
print('-'* 10)
print(arr2d[:2][1:])
print('-'* 10)
print(arr2d[:2, 1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------
[[1 2 3]
 [4 5 6]]
----------
[[4 5 6]]
----------
[[2 3]
 [5 6]]


In [123]:
print(arr2d[1])
print(arr2d[1][:2])
print(arr2d[1, :2])

[4 5 6]
[4 5]
[4 5]


In [124]:
print(arr2d) # 3x3 array
print('-'*10)
print(arr2d[:2]) # arr2d 1행~2행
print('-'*10)
# print(arr2d[:2][2]) //error
# arr2d[:2]의 index[2]열
print(arr2d[:2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------
[[1 2 3]
 [4 5 6]]
----------
[3 6]


In [125]:
# arr2d의 전체 행중 index[0]열값
# arr2d[:, :1] != arr2d[:,0]
print(arr2d[:, 0])
print(arr2d[:, 0].shape, arr2d[:, 0].ndim)
print('-'*10)
print(arr2d[:, :1])
print(arr2d[:, :1].shape, arr2d[:, :1].ndim)

[1 4 7]
(3,) 1
----------
[[1]
 [4]
 [7]]
(3, 1) 2


In [130]:
print(arr2d)
print('-'*10)
print(arr2d[:2])
print('-'*10)
print(arr2d[:2, 1:])
print('-'*10)
arr2d[:2, 1:] = 0
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------
[[1 2 3]
 [4 5 6]]
----------
[[2 3]
 [5 6]]
----------
[[1 0 0]
 [4 0 0]
 [7 8 9]]


### Boolean Indexing

In [158]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print('-'*50)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
--------------------------------------------------
[[ 0.25340354  1.56605018 -0.62037238 -1.36229511]
 [-2.60818604 -2.12102055  0.88704813  0.25794887]
 [-0.48485192 -0.63536543  0.41232938 -0.55847667]
 [-0.0376478  -0.34125371 -0.56773841  1.42366876]
 [-0.1127224   0.61088071  0.24096778  0.11661178]
 [ 0.48367522  0.5430887  -2.33432282  0.0737498 ]
 [-1.2106473   1.04952233 -1.04897364 -0.45582201]]


In [159]:
# 배열 내 boolean 색인으로 True,False 구분
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [160]:
# boolean색인이 True인 data array
print(data[names == 'Bob'])

[[ 0.25340354  1.56605018 -0.62037238 -1.36229511]
 [-0.0376478  -0.34125371 -0.56773841  1.42366876]]


In [161]:
# boolean색인이 True인 data array 중 column이 2이상
print (data[names == 'Bob', 2:])
print('-'*30)
# boolean색인이 True인 data array 중 column이 3
print (data[names == 'Bob', 3])

[[-0.62037238 -1.36229511]
 [-0.56773841  1.42366876]]
------------------------------
[-1.36229511  1.42366876]


In [162]:
# boolean색인 조건 중첩
mask = (names == 'Bob') | (names == 'Will')
print(mask)
print(data[mask])

[ True False  True  True  True False False]
[[ 0.25340354  1.56605018 -0.62037238 -1.36229511]
 [-0.48485192 -0.63536543  0.41232938 -0.55847667]
 [-0.0376478  -0.34125371 -0.56773841  1.42366876]
 [-0.1127224   0.61088071  0.24096778  0.11661178]]


In [163]:
# data array 값이 0보다 작을 경우 0으로 치환
data[data < 0] = 0
data

array([[0.25340354, 1.56605018, 0.        , 0.        ],
       [0.        , 0.        , 0.88704813, 0.25794887],
       [0.        , 0.        , 0.41232938, 0.        ],
       [0.        , 0.        , 0.        , 1.42366876],
       [0.        , 0.61088071, 0.24096778, 0.11661178],
       [0.48367522, 0.5430887 , 0.        , 0.0737498 ],
       [0.        , 1.04952233, 0.        , 0.        ]])

In [164]:
# name이 'Joe'가 아닌 값(boolean색인이 True)을 7로 변환
print(names !='Joe')
data[names != 'Joe'] = 7
print(data)

[ True False  True  True  True False False]
[[7.         7.         7.         7.        ]
 [0.         0.         0.88704813 0.25794887]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [0.48367522 0.5430887  0.         0.0737498 ]
 [0.         1.04952233 0.         0.        ]]


### Transposing Arrays and Swapping Axes

In [43]:
arr = np.arange(15).reshape((3, 5))
arr
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [44]:
arr = np.random.randn(6, 3)
arr
np.dot(arr.T, arr)

array([[6.17700016, 6.91455464, 2.19076939],
       [6.91455464, 9.8045089 , 2.07860265],
       [2.19076939, 2.07860265, 6.00015339]])

In [45]:
arr = np.arange(16).reshape((2, 2, 4))
arr
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [46]:
arr
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## Universal Functions: Fast Element-Wise Array Functions

In [165]:
# arr의 square root
arr = np.arange(10)
print(arr)
np.sqrt(arr)

[0 1 2 3 4 5 6 7 8 9]


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [168]:
# x, y array 최대값 
x = np.random.randn(8)
y = np.random.randn(8)
print(x)
print(y)
print(np.maximum(x, y))

[-0.89182857  0.10127163  0.15299968  1.14092806 -0.42707153 -2.4524623
  1.73317026 -0.37947856]
[ 0.34865697  0.69460575  0.07156145  0.98926913 -0.65305398 -0.8917619
  1.1233102  -0.41281345]
[ 0.34865697  0.69460575  0.15299968  1.14092806 -0.42707153 -0.8917619
  1.73317026 -0.37947856]


In [175]:
# array를 나머지와 몫으로 구분
arr = np.random.randn(7) * 5
print(arr)
print('-'*30)
remainder, whole_part = np.modf(arr)
print(remainder)
print('-'*30)
print(whole_part)
print('-'*30)
print(np.modf(arr))

[ 2.01793589  2.13178143  4.16184367 -4.2176095   2.28801353  0.75839487
 -1.8347202 ]
------------------------------
[ 0.01793589  0.13178143  0.16184367 -0.2176095   0.28801353  0.75839487
 -0.8347202 ]
------------------------------
[ 2.  2.  4. -4.  2.  0. -1.]
------------------------------
(array([ 0.01793589,  0.13178143,  0.16184367, -0.2176095 ,  0.28801353,
        0.75839487, -0.8347202 ]), array([ 2.,  2.,  4., -4.,  2.,  0., -1.]))


In [176]:
arr
np.sqrt(arr)
np.sqrt(arr, arr)
arr

<ipython-input-176-bcce5ef9aa78>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)
<ipython-input-176-bcce5ef9aa78>:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([1.4205407 , 1.46006213, 2.04005972,        nan, 1.5126181 ,
       0.8708587 ,        nan])

### Expressing Conditional Logic as Array Operations

In [182]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [183]:
# cond가 True이면 xarr, False이면 yarr에서 색인
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [178]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [185]:
# arr > 0 이 True면 2, False면 -2
arr = np.random.randn(4, 4)
arr
arr > 0
np.where(arr > 0, 2, -2)

array([[-2, -2, -2,  2],
       [ 2,  2, -2,  2],
       [ 2,  2, -2, -2],
       [-2, -2, -2, -2]])

In [186]:
np.where(arr > 0, 2, arr) # set only positive values to 2

array([[-0.0074813 , -1.14878515, -0.20009271,  2.        ],
       [ 2.        ,  2.        , -1.1438883 ,  2.        ],
       [ 2.        ,  2.        , -1.19059343, -1.7322768 ],
       [-1.79743867, -1.17732553, -0.97350278, -1.07383697]])

### Mathematical and Statistical Methods

In [187]:
# mean() array의 산술평균
# sum() array 각 요소의 합
arr = np.random.randn(5, 4)
arr
arr.mean()
np.mean(arr)
arr.sum()

7.520823527537888

In [190]:
# axis=? 축
print(arr.mean(axis=1))
print(arr.sum(axis=0))

[0.03575686 0.0338228  0.68205923 0.08105213 1.04751486]
[ 2.96816378 -1.73456631  6.15614023  0.13108583]


In [192]:
# cumsum = 누적 합
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
print(arr.cumsum())

[ 0  1  3  6 10 15 21 28]


In [193]:
# cumprod 누적 곱
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr
arr.cumsum(axis=0)
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

### Methods for Boolean Arrays

In [197]:
arr = np.random.randn(100)
(arr > 0).sum() # Number of positive values

48

In [198]:
bools = np.array([False, False, True, False])
bools.any()
bools.all()

False

### Sorting

In [199]:
# 정렬
arr = np.random.randn(6)
arr
arr.sort()
arr

array([-1.29176228, -1.24234965, -0.82749057, -0.65669599, -0.65226587,
        1.308601  ])

In [200]:
arr = np.random.randn(5, 3)
arr
arr.sort(1)
arr

array([[-1.08876998, -0.55117999, -0.52971131],
       [-1.26712658,  0.85460977,  1.86507115],
       [-0.90237982,  0.41111635,  1.14356944],
       [-1.84665521, -0.18128621,  0.44834512],
       [-0.17397925,  1.75876075,  2.60848151]])

In [201]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 5% quantile

-1.613700361217172