<!--NAVIGATION-->
<[step04 NumpyBasic학습](step04_NumpyBasic.ipynb)>  |  <[step06 review](step06_review김성호.ipynb) >

## ufunc 함수라 불림 ##
- ndarray 내에 있는 데이터 원소별로 연산을 수행하는 함수
 하나 이상의 스칼라 값을 받아서 하나 이상의 스칼라 결과 값을 반환하는 간단한 함수를
 고속으로 수행 할 수 있는 벡터화된 래퍼 함수
- 함수의 종류
 단항 유니버설 함수 : 하나의 인자를 받아서 반환
 이항 유니버설 함수 : 두개의 인자를 받아서 단일 배열 반환
- url
https://docs.scipy.org/doc/numpy/reference/ufuncs.html#ufunc

In [2]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# 제곱근
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
# 두개의 배열들의 각 index와 일치되는 요소들끼리만 비교해서 최대값 구하기
x = np.random.randint(100, 999 , size=3)
print(x)

y = np.random.randint(100, 999 , size=3)
print(y)

[179 667 738]
[152 131 531]


In [7]:
# 이항 유니버셜 함수
np.minimum(x, y)

array([152, 131, 531])

In [16]:
data = np.arange(12).reshape(3,4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
data * data

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [18]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
data.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [20]:
# 3x4 x 4x3  = 3x3
data1 = np.dot(data, data.T)
data1

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [24]:
data1 * 2

array([[ 28,  76, 124],
       [ 76, 252, 428],
       [124, 428, 732]])

# 차원축소 집계 연산

In [25]:
x = np.array([1, 2, 10, 3, 4, 20, 40, 100])

In [26]:
x.max()

100

In [27]:
x.min()

1

In [28]:
x.sum()

180

In [29]:
# 가장 큰 데이터의 index값
# 대량의 데이터 분석 시에 확률적으로 높은 데이터 도출시에 필수적으로 사용
x.argmax()

7

In [31]:
a = np.sort(x)
a

array([  1,   2,   3,   4,  10,  20,  40, 100])

In [32]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [34]:
b = np.sort(a)
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [36]:
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [40]:
# 각 행별로 오름차순으로 정렬
b =np.sort(a, axis=1)
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [39]:
# 각 행간에 열을 기준으로 오름차순정렬
b =np.sort(a, axis=0)
b

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

### seed를 활용하는 기술

난수 발생의 기준점을 설정하는 방법

- 필요성 : 향후 ML/DL의 모델 개발시에 정확한 예측에 가까운 패턴을 도출하기 위해서 수많은 다양한 경우의 수로 학습,  <br>
학습시에 난수 발생해서 학습 ( 개발자가 직접 수치 선별해서 입력은 어렵기 때문에 난수로직 활용)

- 난수 : 정해진 범위 내의 알 수 없는 숫자를 도출하는 원리

- 컴퓨터 내부에는 난수 발생하는 로직을 seed라는 기준 데이터를 기반으로 고정화 할 수 있음

In [78]:
np.random.rand(5)

array([0.66652971, 0.38447826, 0.59344542, 0.07730985, 0.51581016])

In [79]:
np.random.seed(42)

In [80]:
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [81]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])